### ISSUE TITLE
Recommend Song on turn

### ISSUE THREAD

**Issue by DevilGale** [jadedtdt/MusicBot#9]
When it is going to be that persons time to have a song played from their list, they can recommend a song from their list. (~recommend) [bot responds] (~value of song in a list)

**Comment by jadedtdt** [comment]
an issue with requiring responses is that it can be confusing for other people/if the person doesnt respond

**Comment by DevilGale** [comment]
Ok worse idea then. It PM's them and if they don't respond by the next song it forgets the request.

**Comment by jadedtdt** [comment]
mood replaces this
